---
title: 'SQL: Advanced SQL Commands - String Functions and Operators'
author: "Sulman Khan"
date: "`r format(Sys.time(), ' %B %d, %Y')`"
output: 
  html_document:
    css: C:/Users/sulma/OneDrive/Desktop/Data Science/Machine Learning/gf_small_touches.css
    highlight: tango
    mathjax: default
    theme: cerulean
---

```{r setup, cache = FALSE, echo = FALSE, message = FALSE, warning = FALSE, tidy = FALSE}
require(knitr)
options(width = 300 , scipen = 5)
options(dplyr.print_max = 200)
# options(width = 100, digits = 7)
opts_chunk$set(message = FALSE, error = FALSE, warning = FALSE, 
               collapse = TRUE, tidy = FALSE,
               cache = TRUE, cache.path = '.cache/', 
               fig.align = 'left', dpi = 100, fig.path = 'figures/Introductiontotextanalytics/')
# opts_chunk$set(dev="png", 
#                dev.args=list(type="cairo"),
#                dpi=96)
```
---

## SQL: JOINS - Advanced SQL Commands - String Function and Operators


### String Functions

The String functions examine and manipulate string values. More information on [String Functions and Operators](https://www.postgresql.org/docs/9.1/functions-string.html)

**Syntax**: 

```{sql, eval = FALSE}
-- String Function
SELECT column_1 || column_2 as new_column
FROM table_1;
```


**Example**: Concatenate the first name and last name columns in the customer table

```{sql, eval = FALSE}
-- Concatenate the first name and last name columns in the customer table
SELECT first_name || ' ' || last_name  AS full_name
FROM customer
limit 20;
```

```{r, echo=FALSE, message=FALSE}
library(RPostgreSQL)
connPostgres = dbConnect(
  dbDriver("PostgreSQL"), dbname="dvdrental", 
  host="localhost", port=5432, 
  user="postgres", password="asshole"
)
DBI::dbGetQuery(connPostgres,"
SELECT first_name || ' ' || last_name  AS full_name
FROM customer
limit 20
")
```

**Example**: Return the uppercase of the first and last names

```{sql, eval = FALSE}
-- Return the uppercase of the first and last names
SELECT upper(first_name), upper(last_name)
FROM customer
limit 20;
```

```{r, echo=FALSE, message=FALSE}
library(RPostgreSQL)
connPostgres = dbConnect(
  dbDriver("PostgreSQL"), dbname="dvdrental", 
  host="localhost", port=5432, 
  user="postgres", password="asshole"
)
DBI::dbGetQuery(connPostgres,"
SELECT upper(first_name), upper(last_name)
FROM customer
limit 20
")
```