---
title: 'SQL: Statement Fundamentals - SELECT'
author: "Sulman Khan"
date: "`r format(Sys.time(), ' %B %d, %Y')`"
output: 
  html_document:
    css: C:/Users/sulma/OneDrive/Desktop/Data Science/Machine Learning/gf_small_touches.css
    highlight: tango
    mathjax: default
    theme: cerulean
---

```{r setup, cache = FALSE, echo = FALSE, message = FALSE, warning = FALSE, tidy = FALSE}
require(knitr)
options(width = 300 , scipen = 5)
options(dplyr.print_max = 200)
# options(width = 100, digits = 7)
opts_chunk$set(message = FALSE, error = FALSE, warning = FALSE, 
               collapse = TRUE, tidy = FALSE,
               cache = TRUE, cache.path = '.cache/', 
               fig.align = 'left', dpi = 100, fig.path = 'figures/Introductiontotextanalytics/')
# opts_chunk$set(dev="png", 
#                dev.args=list(type="cairo"),
#                dpi=96)
```
---

## SQL: Statement Fundamentals

### SELECT

The SELECT function returns the queries indicated in the rows and columns from a database.

**Syntax**: 

```{sql, eval = FALSE}
-- Selects column_1, column_2 and rows from table_name
SELECT column_1, column_2
FROM table_name;
-- Selects all columns and rows from table_name, * = all columns
SELECT *     
FROM table_name;
```


**Example**: Obtain the first name and last name from the actor table.

```{sql, eval = FALSE}
-- Selects the first and last names from the actor table
SELECT first_name, last_name 
FROM actor;
```

```{r, echo=FALSE, message=FALSE}
library(RPostgreSQL)
connPostgres = dbConnect(
  dbDriver("PostgreSQL"), dbname="dvdrental", 
  host="localhost", port=5432, 
  user="postgres", password="asshole"
)
DBI::dbGetQuery(connPostgres,"SELECT first_name, last_name FROM actor")
```

#### Challenge

**Problem**: Use the SELECT statement to obtain the first name, last name, and e-mail address of customers

```{sql, eval = FALSE}
-- Selects the first name, last name, and e-mail addresses of customers
SELECT first_name, last_name, email   
FROM customer;
```

```{r, echo=FALSE, message=FALSE}
library(RPostgreSQL)
connPostgres = dbConnect(
  dbDriver("PostgreSQL"), dbname="dvdrental", 
  host="localhost", port=5432, 
  user="postgres", password="asshole"
)
DBI::dbGetQuery(connPostgres,"SELECT first_name, last_name, email FROM customer")
```

