---
title: 'SQL: Statement Fundamentals - IN'
author: "Sulman Khan"
date: "`r format(Sys.time(), ' %B %d, %Y')`"
output: 
  html_document:
    css: C:/Users/sulma/OneDrive/Desktop/Data Science/Machine Learning/gf_small_touches.css
    highlight: tango
    mathjax: default
    theme: cerulean
---

```{r setup, cache = FALSE, echo = FALSE, message = FALSE, warning = FALSE, tidy = FALSE}
require(knitr)
options(width = 300 , scipen = 5)
options(dplyr.print_max = 200)
# options(width = 100, digits = 7)
opts_chunk$set(message = FALSE, error = FALSE, warning = FALSE, 
               collapse = TRUE, tidy = FALSE,
               cache = TRUE, cache.path = '.cache/', 
               fig.align = 'left', dpi = 100, fig.path = 'figures/Introductiontotextanalytics/')
# opts_chunk$set(dev="png", 
#                dev.args=list(type="cairo"),
#                dpi=96)
```
---

## SQL: Statement Fundamentals


### IN

IN operator with the WHERE clause to check if a value matches any value in a list of values.

**Syntax**:

```{sql, eval = FALSE}
-- IN
SELECT column_1, column_2
FROM table_name
WHERE value IN (SELECT value FROM table_name);
```

**Example**: Rental information and customer_ID are 1 and 2

```{sql, eval = FALSE}
-- Rental information and customer_ID are 1 and 2
SELECT customer_ID, rental_ID, return_date
FROM rental
WHERE customer_ID IN (1,2)
ORDER BY return_date DESC;
````

```{r, echo=FALSE, message=FALSE}
library(RPostgreSQL)
connPostgres = dbConnect(
  dbDriver("PostgreSQL"), dbname="dvdrental", 
  host="localhost", port=5432, 
  user="postgres", password="asshole"
)
DBI::dbGetQuery(connPostgres,
"
SELECT customer_ID, rental_ID, return_date
FROM rental
WHERE customer_ID IN (1,2)
ORDER BY return_date DESC
")
```

**Example**: Rental information and customer_ID are not 1 and 2

```{sql, eval = FALSE}
-- Rental information and customer_ID are not 1 and 2
SELECT customer_ID, rental_ID, return_date
FROM rental
WHERE customer_ID NOT IN (1,2)
ORDER BY return_date DESC;
````

```{r, echo=FALSE, message=FALSE}
library(RPostgreSQL)
connPostgres = dbConnect(
  dbDriver("PostgreSQL"), dbname="dvdrental", 
  host="localhost", port=5432, 
  user="postgres", password="asshole"
)
DBI::dbGetQuery(connPostgres,
"
SELECT customer_ID, rental_ID, return_date
FROM rental
WHERE customer_ID NOT IN (1,2)
ORDER BY return_date DESC
")
```

**Example**: Select all columns from the payment table where the amount is either \$7.99 or \$8.99

```{sql, eval = FALSE}
-- Select all columns from the payment table where the amount is \$7.99 or \$8.99
SELECT *
FROM payment
WHERE amount IN (7.99,8.99);
````

```{r, echo=FALSE, message=FALSE}
library(RPostgreSQL)
connPostgres = dbConnect(
  dbDriver("PostgreSQL"), dbname="dvdrental", 
  host="localhost", port=5432, 
  user="postgres", password="asshole"
)
DBI::dbGetQuery(connPostgres,
"
SELECT *
FROM payment
WHERE amount IN (7.99,8.99)
")
```
