---
title: 'SQL: Creating Databases and Tables - Update'
author: "Sulman Khan"
date: "`r format(Sys.time(), ' %B %d, %Y')`"
output: 
  html_document:
    css: C:/Users/sulma/OneDrive/Desktop/Data Science/Machine Learning/gf_small_touches.css
    highlight: tango
    mathjax: default
    theme: cerulean
---

```{r setup, cache = FALSE, echo = FALSE, message = FALSE, warning = FALSE, tidy = FALSE}
require(knitr)
options(width = 300 , scipen = 5)
options(dplyr.print_max = 200)
# options(width = 100, digits = 7)
opts_chunk$set(message = FALSE, error = FALSE, warning = FALSE, 
               collapse = TRUE, tidy = FALSE,
               cache = TRUE, cache.path = '.cache/', 
               fig.align = 'left', dpi = 100, fig.path = 'figures/Introductiontotextanalytics/')
# opts_chunk$set(dev="png", 
#                dev.args=list(type="cairo"),
#                dpi=96)
```
---

## SQL: Creating Databases and Tables - UPDATE


### UPDATE

The UPDATE function changes the values of the columns in a table.




**Syntax**: 

```{sql, eval = FALSE}
-- Update
UPDATE table
SET column1 = value1,
    column_2 = value2, ...
WHERE condition;

```


**Example**: Update Link

```{sql, eval = FALSE}
-- Update
UPDATE link
SET description = 'Empty Description';

```

```{r, echo=FALSE, message=FALSE}
library(RPostgreSQL)
connPostgres = dbConnect(
  dbDriver("PostgreSQL"), dbname="learning", 
  host="localhost", port=5432, 
  user="postgres", password="asshole"
)
DBI::dbGetQuery(connPostgres,"
UPDATE link
SET description = 'Empty Description'
")
```

```{sql, eval = FALSE}
-- Select
SELECT * FROM link;

```

```{r, echo=FALSE, message=FALSE}
library(RPostgreSQL)
connPostgres = dbConnect(
  dbDriver("PostgreSQL"), dbname="learning", 
  host="localhost", port=5432, 
  user="postgres", password="asshole"
)
DBI::dbGetQuery(connPostgres,"
SELECT * FROM link
")
```

**Example**: Update Link with WHERE

```{sql, eval = FALSE}
-- Update description with A
UPDATE link
SET description = 'Name starts with an A'
WHERE name LIKE 'A%';

```

```{r, echo=FALSE, message=FALSE}
library(RPostgreSQL)
connPostgres = dbConnect(
  dbDriver("PostgreSQL"), dbname="learning", 
  host="localhost", port=5432, 
  user="postgres", password="asshole"
)
DBI::dbGetQuery(connPostgres,"
UPDATE link
SET description = 'Name starts with an A'
WHERE name LIKE 'A%'
")
```

```{sql, eval = FALSE}
-- Select
SELECT * FROM link;

```

```{r, echo=FALSE, message=FALSE, new}
library(RPostgreSQL)
connPostgres = dbConnect(
  dbDriver("PostgreSQL"), dbname="learning", 
  host="localhost", port=5432, 
  user="postgres", password="asshole"
)
DBI::dbGetQuery(connPostgres,"
SELECT * FROM link
")
```

**Example**: Update Link with another column

```{sql, eval = FALSE}
-- Update description with name
UPDATE link
SET description = name;

```

```{r, echo=FALSE, message=FALSE}
library(RPostgreSQL)
connPostgres = dbConnect(
  dbDriver("PostgreSQL"), dbname="learning", 
  host="localhost", port=5432, 
  user="postgres", password="asshole"
)
DBI::dbGetQuery(connPostgres,"
UPDATE link
SET description = name
")
```

```{sql, eval = FALSE}
-- Select
SELECT * FROM link;

```

```{r, echo=FALSE, message=FALSE, new1}
library(RPostgreSQL)
connPostgres = dbConnect(
  dbDriver("PostgreSQL"), dbname="learning", 
  host="localhost", port=5432, 
  user="postgres", password="asshole"
)
DBI::dbGetQuery(connPostgres,"
SELECT * FROM link
")
```